import 'dart:ffi';
import 'dart:io';

void main(){

  stdout.write("\nDigite um valor para 'A': ");
  int valor1 = int.parse(stdin.readLineSync()!);

  stdout.write("\nDigite um valor para 'B': ");
  int valor2 = int.parse(stdin.readLineSync()!);

  stdout.write("\nDigite um valor para 'C': ");
  int valor3 = int.parse(stdin.readLineSync()!);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                   